name: Build Docker Image

on: 
  push:
    branches:
      - master
      
jobs:
  build-step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: docker build & push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/nocd .
          docker push ghcr.io/${{ github.repository_owner }}/nocd