name: Build Docker Image

on: 
  push:
    branches:
      - master
      
jobs:
  build-step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: docker build & push
        env:
          DockerPassword: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          docker build --no-cache -t docker.pkg.github.com/naiba/dockerfiles/nocd .
          docker login -u naiba -p $DockerPassword docker.pkg.github.com
          docker push docker.pkg.github.com/naiba/dockerfiles/nocd